names:
- Traffic Signal
- Lamp Post
- Zebra Crossing
- Bike
- Car
- Rikshaw
- Tyre Works
- Tree
- Tractor
- Cattle
- Vegetation
- Electricity Pole
- Building
- Board
- Wall
- Person
- Bus
- Bridge
- Road Divider
- Tempo
- Traffic Sign Board
- Flag
- Crane
- Cycle
- Dog
- Truck
- Glove
- Overbridge
- Manhole
- Bus Stop
- Barricade
- Petrol Pump
- Ambulance
- Goat
- Cart
nc: 35
train: /content/data1/images/train
val: /content/data1/images/val
